#!/usr/bin/expect

set timeout 2

log_file ../../log.txt

set expect_file [open [lindex $argv 0]]
set expect_lines [split [read $expect_file] "\n"]
close $expect_file

set input_file [open [lindex $argv 1]]
set input_lines [split [read $input_file] "\n"]
close $input_file

spawn java -jar ../../../target/afkQuinterac-1.0-SNAPSHOT.jar accounts.txt ../../output_transactions.txt

set i 0
foreach line $expect_lines {
	expect {
		$line {}
		timeout {
			send_log "\n\n\nExpected: $line \n"
			exit 1
		}
	}
	
	if { $i < [llength $input_lines] } {
		set s [lindex $input_lines $i]
		send "$s\n"
	}
	
	
	incr i 1
}

exit 0
