name: Quinterac CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: sudo apt install expect
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile with Maven
      run: mvn -DskipTests clean compile package
    - name: Testing
      run: chmod 777 run_test.sh && bash run_test.sh
    - name: package
      run: mvn package
